source "https://rubygems.org"

gem "rails", "~> 8.0.1"
gem "mysql2"
gem "puma"
gem "bcrypt"
gem "httparty"
gem "rack-cors"
gem "bootsnap", require: false
gem "activerecord-import"

group :development, :test do
  gem "pry-rails"
  gem "debug"
  gem "brakeman", require: false
  gem "rubocop-rails-omakase", require: false
  gem "factory_bot_rails"
  gem "rspec-rails"
end
